
-- 保存クエリ名>>  2023-11-30 17:06:51

create or replace table `lixil-workspace.an1_kyoko1kato.extEng_4dairyReport` as (

  with
  result_cur as (
    SELECT
      YEAR_MONTH,
      ZKSLV1GRU, ZKSLV1GRT,
      ZKSLV2GRU, ZKSLV2GRT,
      ZKSLV3GRU, ZKSLV3GRT,
      ZKSLV4GRU, ZKSLV4GRT,
      ZKSLV5GRU, ZKSLV5GRT,
      ZKSLV6GRU, ZKSLV6GRT,
      ZKSLV7GRU, ZKSLV7GRT,
      ZZ_IRONG, ZZ_IRONG_TEXT,
      T_GOODS_CLASS_CD, T_GOODS_CLASS_TEXT,
      S_GOODS_CLASS_CD, S_GOODS_CLASS_TEXT,
      Q_GOODS_CLASS_CD, Q_GOODS_CLASS_TEXT,
      P_GOODS_CLASS_CD, P_GOODS_CLASS_TEXT,
      N_GOODS_CLASS_CD, N_GOODS_CLASS_TEXT,
      M_GOODS_CLASS_CD, M_GOODS_CLASS_TEXT,
      K_GOODS_CLASS_CD, K_GOODS_CLASS_TEXT,
      AMOUNT,
      SALES_PROFIT,
      STD_PROFIT,
      '' as DATA_DIV,
      0 as ORDER_BACKLOG_CONFIRM,
      0 as ORDER_BACKLOG_HOPE,
      0 as ORDER_BACKLOG_ALL,
      0 as ORDER_BACKLOG_EOM,
      0 as ORDER_AMOUNT
    FROM `lixil-dwh.pii_an1_acct_sales_controlling.T_SALES_RESULTS_SUMMARY`
    WHERE
      T_GOODS_CLASS_CD = 'T41334'
      -- and ZKSLV4GRU = 'B101400030'
      AND YEAR_MONTH = FORMAT_DATE('%Y%m',CURRENT_DATE('Asia/Tokyo'))
  ),

  result_pre as (
    SELECT
      cast(cast(YEAR_MONTH as int64) -100 as string) as YEAR_MONTH,
      ZKSLV1GRU, ZKSLV1GRT,
      ZKSLV2GRU, ZKSLV2GRT,
      ZKSLV3GRU, ZKSLV3GRT,
      ZKSLV4GRU, ZKSLV4GRT,
      ZKSLV5GRU, ZKSLV5GRT,
      ZKSLV6GRU, ZKSLV6GRT,
      ZKSLV7GRU, ZKSLV7GRT,
      ZZ_IRONG, ZZ_IRONG_TEXT,
      T_GOODS_CLASS_CD, T_GOODS_CLASS_TEXT,
      S_GOODS_CLASS_CD, S_GOODS_CLASS_TEXT,
      Q_GOODS_CLASS_CD, Q_GOODS_CLASS_TEXT,
      P_GOODS_CLASS_CD, P_GOODS_CLASS_TEXT,
      N_GOODS_CLASS_CD, N_GOODS_CLASS_TEXT,
      M_GOODS_CLASS_CD, M_GOODS_CLASS_TEXT,
      K_GOODS_CLASS_CD, K_GOODS_CLASS_TEXT,
      PY_AMOUNT as AMOUNT,
      PY_SALES_PROFIT as SALES_PROFIT,
      PY_STD_PROFIT as STD_PROFIT,
      '' as DATA_DIV,
      0 as ORDER_BACKLOG_CONFIRM,
      0 as ORDER_BACKLOG_HOPE,
      0 as ORDER_BACKLOG_ALL,
      0 as ORDER_BACKLOG_EOM,
      0 as ORDER_AMOUNT
    FROM `lixil-dwh.pii_an1_acct_sales_controlling.T_SALES_RESULTS_SUMMARY_BM`
    WHERE
      T_GOODS_CLASS_CD = 'T41334'
      -- and ZKSLV4GRU = 'B101400030'
      AND YEAR_MONTH = FORMAT_DATE('%Y%m',CURRENT_DATE('Asia/Tokyo'))
  ),

  backlog_ as (
    SELECT
      YEAR_MONTH,
      ZKSLV1GRU, ZKSLV1GRT,
      ZKSLV2GRU, ZKSLV2GRT,
      ZKSLV3GRU, ZKSLV3GRT,
      ZKSLV4GRU, ZKSLV4GRT,
      ZKSLV5GRU, ZKSLV5GRT,
      ZKSLV6GRU, ZKSLV6GRT,
      ZKSLV7GRU, ZKSLV7GRT,
      ZZ_IRONG, ZZ_IRONG_TEXT,
      T_GOODS_CLASS_CD, T_GOODS_CLASS_TEXT,
      S_GOODS_CLASS_CD, S_GOODS_CLASS_TEXT,
      Q_GOODS_CLASS_CD, Q_GOODS_CLASS_TEXT,
      P_GOODS_CLASS_CD, P_GOODS_CLASS_TEXT,
      N_GOODS_CLASS_CD, N_GOODS_CLASS_TEXT,
      M_GOODS_CLASS_CD, M_GOODS_CLASS_TEXT,
      K_GOODS_CLASS_CD, K_GOODS_CLASS_TEXT,
      0 as AMOUNT,
      0 as SALES_PROFIT,
      0 as STD_PROFIT,
      DATA_DIV,
      ORDER_BACKLOG_CONFIRM,
      ORDER_BACKLOG_HOPE,
      ORDER_BACKLOG_ALL,
      ORDER_BACKLOG_EOM,
      ORDER_AMOUNT
    FROM `lixil-dwh.pii_an1_acct_sales_controlling.T_ORDER_BACKLOG_SUMMARY`
    WHERE
      T_GOODS_CLASS_CD = 'T41334'
      -- and ZKSLV4GRU = 'B101400030'
      AND YEAR_MONTH = FORMAT_DATE('%Y%m',CURRENT_DATE('Asia/Tokyo'))
  ),

  union_ as (
    select * from result_cur
    union all
    select * from result_pre
    union all
    select * from backlog_
  )

  select
    YEAR_MONTH,
    ZKSLV1GRU, ZKSLV1GRT,
    ZKSLV2GRU, ZKSLV2GRT,
    ZKSLV3GRU, ZKSLV3GRT,
    ZKSLV4GRU, ZKSLV4GRT,
    ZKSLV5GRU, ZKSLV5GRT,
    ZKSLV6GRU, ZKSLV6GRT,
    ZKSLV7GRU, ZKSLV7GRT,
    ZZ_IRONG, ZZ_IRONG_TEXT,
    T_GOODS_CLASS_CD, T_GOODS_CLASS_TEXT,
    S_GOODS_CLASS_CD, S_GOODS_CLASS_TEXT,
    Q_GOODS_CLASS_CD, Q_GOODS_CLASS_TEXT,
    P_GOODS_CLASS_CD, P_GOODS_CLASS_TEXT,
    N_GOODS_CLASS_CD, N_GOODS_CLASS_TEXT,
    M_GOODS_CLASS_CD, M_GOODS_CLASS_TEXT,
    K_GOODS_CLASS_CD, K_GOODS_CLASS_TEXT,
    sum(AMOUNT) as AMOUNT,
    sum(SALES_PROFIT) as SALES_PROFIT,
    sum(STD_PROFIT) as STD_PROFIT,
    DATA_DIV,
    sum(ORDER_BACKLOG_CONFIRM) as ORDER_BACKLOG_CONFIRM,
    sum(ORDER_BACKLOG_HOPE) as ORDER_BACKLOG_HOPE,
    sum(ORDER_BACKLOG_ALL) as ORDER_BACKLOG_ALL,
    sum(ORDER_BACKLOG_EOM) as ORDER_BACKLOG_EOM,
    sum(ORDER_AMOUNT) as ORDER_AMOUNT
  from union_
  group by
    YEAR_MONTH,
    ZKSLV1GRU, ZKSLV1GRT,
    ZKSLV2GRU, ZKSLV2GRT,
    ZKSLV3GRU, ZKSLV3GRT,
    ZKSLV4GRU, ZKSLV4GRT,
    ZKSLV5GRU, ZKSLV5GRT,
    ZKSLV6GRU, ZKSLV6GRT,
    ZKSLV7GRU, ZKSLV7GRT,
    ZZ_IRONG, ZZ_IRONG_TEXT,
    T_GOODS_CLASS_CD, T_GOODS_CLASS_TEXT,
    S_GOODS_CLASS_CD, S_GOODS_CLASS_TEXT,
    Q_GOODS_CLASS_CD, Q_GOODS_CLASS_TEXT,
    P_GOODS_CLASS_CD, P_GOODS_CLASS_TEXT,
    N_GOODS_CLASS_CD, N_GOODS_CLASS_TEXT,
    M_GOODS_CLASS_CD, M_GOODS_CLASS_TEXT,
    K_GOODS_CLASS_CD, K_GOODS_CLASS_TEXT,
    DATA_DIV
);